- name: This is for to test the vaiables in yaml file 
  hosts: localhost
  vars: 
    User: "Hari krishna"
    Course: "Devops"
    Age: 41
  tasks:
  - name: printing the local one variables
    debug:
      msg: "printing the first varaible{{User}}"

  - name: prinitng the local second varible
    debug: 
      msg: "printing the second variable{{Course}}"  
       
  - name: prinitng the local third varible
    debug: 
      msg: "printing the third variable{{Age}}"  
- name: This is for to test the vaiables of list in yaml file 
  hosts: localhost
  vars: 
    - List1:
      - "aakarsh"
      - "karanam"
      - "kumari sireesha"
  tasks:
  - name: printing the local one variables
    debug:
      msg: "printing the first varaible{{List1}}"

- name: This is for to test the vaiables of list in yaml file 
  hosts: localhost
  vars: 
    map1:
      Son: "aakarsh"
      Surname: "karanam"
      wife: "kumari sireesha"
  tasks:
  - name: printing the local one variables
    debug:
      msg: "printing the first varaible{{map1}}"


