- name: this is the first step
  hosts: localhost 
  # variables: 
  #   inventory_hostname: "Hari krishna ansible"
  #   ansible_default_ipv4: "192.103.82.10"
  tasks: 
    name: first printing
    ansible.builtin.debug module:
      msg: "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4 }}"
