- name: Lists
  hosts: localhost
  gather_facts: no
  vars:
    bands:
      - The Beatles
      - Led Zeppelin
      - The Police
      - Rush
    bands2: ['The Beatles', 'Led Zeppelin', 'The Police', 'Rush']
  tasks:

    - name: T01 - List bands 1
      ansible.builtin.debug:
        msg: "{{ bands }}"

    - name: T02 - List bands 2
      ansible.builtin.debug:
        msg: "{{ bands2 }}"

    - name: T03 - Print specific element
      ansible.builtin.debug:
        msg: "{{ bands[0] }}"

    - name: T04 - Process list using a loop
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{  bands }}"

    - name: T05 - Add item to bands2
      ansible.builtin.set_fact:
        bands2: "{{ bands2 + ['Rolling Stones'] }}" 

    - name: T06 - Difference between bands2 and bands
      ansible.builtin.debug:
        msg: "{{ bands2 | difference(bands) }}" 

    - name: T07 - Show the data type of a list
      ansible.builtin.debug:
        msg: "{{ bands | type_debug }}" 