- name: Instaallation of nginx app
  hosts: localhost
  tasks: 
    - name: now start installing the nginx
      ansible.builtin.package:
        name: nginx
        state: present
      become: yes
      become_method: enable
      become_user: root  