- name: Instaallation of nginx app
  hosts: localhost
  become: yes
  #become_method: su
  tasks: 
    - name: now start installing the nginx
      ansible.builtin.package:
    - name: Make sure the current version of ‘sysstat’ is installed.
      dnf:
        name: nginx
        state: latest
  