- name: Instaallation of nginx app
  hosts: localhost
  become: yes

  tasks:
    - name: "Check if NGINX is installed "
      package_facts:
        manager: auto
    - name: NGINX test result
      debug: 
        msg: "NGINX found"
      when: "'nginx' in ansible_facts.packages"

    - name: "NGINX test result"
      debug: 
        msg: "NGINX NOT found"
      when: "'nginx' not in ansible_facts.packages"
    - name: start nginx
      service:
        name: nginx
        state: started
    

  