- name: Instaallation of nginx app
  hosts: localhost
  tasks: 
    - name: now start installing the nginx
      ansible.builtin.package:
    - name: Make sure the current version of ‘sysstat’ is installed.
      dnf:
        name: nginx
        state: latest
      become: yes
      become_method: enable
      become_user: root  