- name: Instaallation of nginx app
  hosts: localhost
  become: yes
  #become_method: su
  tasks: 
    - name: Make sure the nginx installation
      dnf:
        name: nginx
        state: absent
    - name: Make sure the nginx installation
      dnf:
        name: nginx
        state: latest
  