- hosts: localhost
  become: true
  tasks:
    - name: Install required packages
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - php5-cli
        - nginx
        - mysql-server-5.6
    - name: printing the variables from inventory 
      ansible.builtin.debug:
        msg: "User {{ Hari }} is {{son } ({{ Wife }})"    