- name: setting up db server 
  hosts: DB
  vars:
  tasks:
  - name: installing the mysql 
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  - name: printing the installed message
    debug:
      msg: "mysqld installed"