- name: setting up db server 
  hosts: DB
  vars:
  tasks:
    - name: installing the mysql 
      ansible.builtin.dnf:
        -name: mysqld
        -state: installed
    - name: printing the installed message
      debug:
        msg: "mysqld installed"