- name: setting up db server 
  hosts: DB
  vars:
  tasks:
  - name: installing the mysql 
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  - name: mysqld enable service
    ansible.builtin.service:
      name: mysqld
      enabled: yes
  - name: mysqld enable service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  # - name: Get Service Status
  #   ansible.builtin.systemd:
  #     name: mysqld
  #   register: pg_service_status
  #   debug:
  #     msg: pg_service_status.status.ActiveState


  - name: verifying the service is running or not 
    debug:
      msg: "mysqld istarted"