- name: setting up the backend server 
  hosts: Backend
  become: yes
  tasks:

  - name: disabling the nodejs
    ansible.builtin.command: dnf module disable nodejs -y
  - name: enabling the nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Enable service mysqld, and not touch the state
    ansible.builtin.dnf:
      name: nodejs
      state: installed 
  - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
    ansible.builtin.user:
      name: expense
  - name: Run command for setting the password
    ansible.builtin.command: mkdir /app

    
