- name: setting up the DB server 
  hosts: DB
  become: yes
  tasks:
  - name: installing the dependenciew
    ansible.builtin.pip:
      name: 
      - PyMySQL
      - cryptography
  - name: installing the mysql 
    ansible.builtin.dnf:
      name: mysql-server 
      state: latest
  - name: Enable service mysqld, and not touch the state
    ansible.builtin.service:
      name: mysqld
      enabled: yes
  - name: enabling the mysql-d
    ansible.builtin.service:
      name: mysqld
      state: started

  - name: Try to create database as root/nopassword first. If not allowed, pass the credentials
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      loglogin_host: '3.93.17.249' 
      filter: version
    ignore_errors: yes
    register: mysql_info

  - name: printing the messages of DB
    ansible.builtin.debug:
      msg: "log is {{mysql_info}}"
  - name: Run command for setting the password
    ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1
    when: mysql_info.FAILED! is True 