- name: setting up the DB server 
  hosts: DB
  tasks:
  - name: installing the dependenciew
    ansible.builtin.pip:
      name: PyMySQL
  - name: installing the mysql 
    ansible.builtin.dnf:
      name: mysql-server 
      state: latest
  - name: Enable service mysqld, and not touch the state
    ansible.builtin.service:
      name: mysqld
      enabled: yes
  - name: enabling the mysql-d
    ansible.builtin.service:
      name: mysqld
      state: started

  - name: Try to create database as root/nopassword first. If not allowed, pass the credentials
    community.mysql.mysql_db:
      name: Db
      login_user: root
      login_password: ExpenseApp@1
