- name: installation of nginx
  hosts: web
  become: yes
  tasks: 
  - name: install nginx
    ansible.built.dnf:
      name: nginx 
      state: latest
  - name: start nginx
    ansible.built.service:
      service:
      name: nginx
      state: started
      enabled: yes