- name: play3 and tasks1
  hosts: localhost
  vars:
    course: "Devops"
    name: "Harikrishna"
    age: "41"

  tasks:
  - name: printing the tasklevel messange
    vars:
      name: "Aakarsh"
    ansible.builtin.debug:
      msg: "Hi this is {{name}} learning {{course}} and my age is {{age}}" 
  - name: printing the play level messange
    ansible.builtin.debug:
      msg: "Hi this is {{name}} learning {{course}} and my age is {{age}}"     
