- name: printing the variables from file 
  hosts: localhost
  vars_files:
    - variables_1.yml
  tasks:
    - name: printing the variable 
      ansible.builtin.debug:
        msg: "hi this is {{name }} learing {{courese}} and my age is {{age}}"