- name: printg the variables from 
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Please enter your name
  - passwd: passwd
    prompt: Please enter your name
  tasks:
    - name: printg the prompt varibles
      ansible.builtin.debug:
        msg: " printing {{USERNAME}}  is {{passwd}}"